require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'DatalakeFaceLiveness' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  pod 'React-Codegen', :path => '../node_modules/react-native/ReactCommon'
  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'
end
